# Generated by Django 3.2.11 on 2023-07-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='weight',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
