# Generated by Django 3.2.11 on 2023-07-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
