# Generated by Django 3.2.11 on 2023-07-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_order_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
    ]
