# Generated by Django 3.2.11 on 2023-07-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
