# Generated by Django 3.2.11 on 2023-07-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20230717_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
