# Generated by Django 3.2.11 on 2023-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20230717_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(default='happy birthday', max_length=500),
        ),
    ]
