# Generated by Django 4.2.3 on 2023-07-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
