# Generated by Django 4.2.3 on 2023-07-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_topping_cake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
